---
title: "tony_file"
author: "Tony Daza"
date: "2023-03-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(needs)
needs(tidyverse, rio, here, psych)
```

# Innovative School Practices   
## Importing the Data  

Thank you Janette for compiling the data!

```{r import}

load(here("data/canopy-schools.RData"))


```

*After looking at the data, I think we need to combine the tags into one variable as a count of number of practices if we are going to run the model as suggested*

## Counting Number of Practices  

```{r count}
main$prac_tot <- rowSums(main[c(5,6,7,8,9,10,11,12,13)], na.rm=TRUE)

main <- main %>% mutate_at(c('locale'), ~na_if(.,''))

main$locale <- as.factor(main$locale)


count(main)

main %>%
  count(locale)

# Looks like we have 92 NA value schools.

```

## Examining data to model   

```{r desript}

main %>%
  filter(locale != "NA") %>%
  group_by(locale) %>%
ggplot(aes(x = wave, y = prac_tot )) +           
  geom_bar(stat = "summary", fun = "mean", fill="cornflowerblue") + 
  facet_grid(~locale) + 
  theme_classic()+
  labs(y = "Total Practices", x = "Wave")

```

